import { DataTypes } from 'sequelize'
import { sequelize } from './database.js'

export const CandleModel = sequelize.define('Candle', {
    chainId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        primaryKey: true
    },
    token0: {  // address of token
        type: DataTypes.STRING,
        allowNull: false,
        primaryKey: true
    },
    token1: {  // address of token
        type: DataTypes.STRING,
        allowNull: false,
        primaryKey: true
    },
    dex: {  // name of dex, e.g. Uniswap V3, Pancakeswap
        type: DataTypes.STRING,
        allowNull: false,
        primaryKey: true
    },
    timestamp: {
        type: DataTypes.INTEGER,
        allowNull: false,
        primaryKey: true
    },
    o: {    // open
        type: DataTypes.DOUBLE,
        allowNull: false
    },
    h: {    // high
        type: DataTypes.DOUBLE,
        allowNull: false
    },
    l: {    // low
        type: DataTypes.DOUBLE,
        allowNull: false
    },
    c: {    //close
        type: DataTypes.DOUBLE,
        allowNull: false
    }
}, {
    timestamps: false  // disable autogenerated timestamp by sequelize
});