import { DataTypes } from 'sequelize'
import { sequelize } from './database.js'

export const PoolModel = sequelize.define('Pool', {
    id:{
        type:DataTypes.STRING,
        allowNull: false,
        primaryKey: true
    },
    chainId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        // primaryKey: true
    },
    token0Name: {  // name of token
        type: DataTypes.STRING,
        allowNull: false,
        // primaryKey: true
    },
    token0Address: {  // address of token
        type: DataTypes.STRING,
        allowNull: false,
        // primaryKey: true
    },
    token0Symbol: {  // symbol of token
        type: DataTypes.STRING,
        allowNull: false,
        // primaryKey: true
    },
    token1Name: {  // name of token
        type: DataTypes.STRING,
        allowNull: false,
        // primaryKey: true
    },
    token1Address: {  // address of token
        type: DataTypes.STRING,
        allowNull: false,
        // primaryKey: true
    },
    token1Symbol: {  // symbol of token
        type: DataTypes.STRING,
        allowNull: false,
        // primaryKey: true
    },
    volume:{
        type: DataTypes.INTEGER,
        allowNull: true
    }
}, {
    timestamps: false  // disable autogenerated timestamp by sequelize
});