import { DataTypes } from 'sequelize'
import { sequelize } from './database.js'

export const TokenModel = sequelize.define('Token', {
    chainId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        primaryKey: true
    },
    name: {  // name of token
        type: DataTypes.STRING,
        allowNull: false,
        primaryKey: true
    },
    address: {  // address of token
        type: DataTypes.STRING,
        allowNull: false,
        primaryKey: true
    },
    symbol: {  // symbol of token
        type: DataTypes.STRING,
        allowNull: false,
        primaryKey: true
    },
    logoURI: {  // logo URI
        type: DataTypes.STRING,
        allowNull: true
    },
    decimals: {  // decimal of token
        type: DataTypes.INTEGER,
        allowNull: true
    },
    volume:{
        type: DataTypes.INTEGER,
        allowNull: true
    }
}, {
    timestamps: false  // disable autogenerated timestamp by sequelize
});